name: 'Summarize Repositories'
on:
  workflow_dispatch:
    inputs:
      org_name:
        description: 'GitHub Organization Name'
        required: true
        type: string
jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Generate Repository Summaries
        uses: ./
        with:
          org_name: ${{ inputs.org_name }}
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.MY_OPENAI_API_KEY }}
      
      # Add this step to save the output
      - name: Upload Summary File
        uses: actions/upload-artifact@v3
        with:
          name: repository-summaries-${{ inputs.org_name }}
          path: portfolio_summaries.json
