name: 'Summarize Repositories'

on:
  workflow_dispatch:
    inputs:
      org_name:
        description: 'GitHub Organization Name'
        required: true
        type: string

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Repository Summaries
        uses: ./  # If action is in same repo, or org/repo-name if external
        with:
          org_name: ${{ inputs.org_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
